settings:
  title: 'Novacrypt Status Page'
  url: 'https://status.novacrypt.org' # used for Slack messages
  logo: novacrypt.webp # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:

  - id: novacrypt-site
    name: novacrypt.org
    description: 'Novacrypt'
    url: 'https://novacrypt.org'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
    
  - id: novacrypt-us
    name: 'Novacrypt US Server'
    description: 'Novacrypt US Server'
    url: 'https://98.116.218.208:443/'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: novacrypt-eu
    name: 'Novacrypt EU Server'
    description: 'Novacrypt EU Server'
    url: 'https://3.122.229.191:443/ '
    method: GET
    expectStatus: 200
    linkable: false 
